// frontend/src/components/GlassCard.vue
<template>
  <div
    :class="[
      'bg-[rgb(var(--card))] rounded-[var(--radius-lg)] p-5 border border-white/5 shadow-card',
      hover ? 'shadow-card hover:shadow-card-hover active:scale-95 transition-base cursor-pointer' : '',
      className
    ]"
    @click="onClick"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
defineProps<{
  hover?: boolean
  className?: string
  onClick?: () => void
}>()
</script>

// figma/Dark Mode Health App UI/src/components/GlassCard.tsx
import { ReactNode } from "react";

interface GlassCardProps {
  children: ReactNode;
  className?: string;
  hover?: boolean;
  onClick?: () => void;
}

export function GlassCard({ children, className = "", hover = false, onClick }: GlassCardProps) {
  return (
    <div 
      onClick={onClick}
      className={`
        bg-[rgb(var(--card))] rounded-[var(--radius-lg)] p-5 
        border border-white/5 shadow-card
        ${hover ? 'hover:shadow-card-hover active:scale-[0.98] cursor-pointer transition-all' : ''}
        ${className}
      `}
    >
      {children}
    </div>
  );
}
